package argvine

import (
	"fmt"
	"sort"
	"strings"
)

// Bash returns a bash completion script for the tree rooted at root.
//
// EN — When the user presses TAB it is bash, not this program, that has to
// answer. Bash runs a shell function and expects the list of possible words
// back — but that list depends on where the user is in the command tree, and a
// shell script has no access to a Go structure.
//
// So the tree is FLATTENED, once, into a case statement with one arm per node:
//
//	case "$key" in
//	    "task")            COMPREPLY=($(compgen -W "add done list remote --help --verbose" -- "$cur"));;
//	    "task remote")     COMPREPLY=($(compgen -W "add --help --verbose" -- "$cur"));;
//	    "task remote add") COMPREPLY=($(compgen -W "--help --verbose" -- "$cur"));;
//	esac
//
// The full path of a node becomes the KEY; whatever may follow it becomes the
// VALUE. The generated function rebuilds that key from what the user has typed.
//
// Like Help, this returns a string and never writes anywhere. And like Help, it
// reads only the tree: a subcommand or flag you add becomes completable without
// anyone editing this file.
//
// PT — Quando o usuário aperta TAB, quem tem que responder é o bash, não este
// programa. O bash roda uma função de shell e espera de volta a lista de
// palavras possíveis — mas essa lista depende de onde o usuário está na árvore
// de comandos, e um script de shell não tem acesso a uma estrutura Go.
//
// Então a árvore é ACHATADA, uma vez, num case com um braço por nó. O caminho
// completo do nó vira a CHAVE; o que pode segui-lo vira o VALOR. A função gerada
// reconstrói essa chave a partir do que o usuário digitou.
//
// Como o Help, devolve string e nunca escreve em lugar nenhum. E como o Help, lê
// só a árvore: um subcomando ou flag que você acrescenta fica completável sem
// ninguém editar este arquivo.
func Bash(root *Command) string {
	fn := "_" + sanitize(root.Name) + "_completions"

	var arms []string
	collectArms(root, []string{root.Name}, nil, &arms)

	var b strings.Builder

	// EN: The leading "#" is not decoration — without it the line is a COMMAND,
	// and sourcing the script would try to run "bash completion for task".
	// `bash -n` would not catch that: it checks syntax, and a bare command line
	// is perfectly valid syntax. This is exactly why the milestone requires
	// pressing TAB in a real terminal rather than trusting the parser check.
	// PT: O "#" inicial não é enfeite — sem ele a linha é um COMANDO, e dar
	// source no script tentaria rodar "bash completion for task". O `bash -n`
	// não pegaria isso: ele checa sintaxe, e uma linha de comando solta é
	// sintaxe perfeitamente válida. É justamente por isso que o marco exige
	// apertar TAB num terminal de verdade em vez de confiar na checagem.
	b.WriteString("# bash completion for " + root.Name + "\n")
	b.WriteString("# generated by argvine -- do not edit by hand\n\n")

	b.WriteString(fn + "() {\n")

	// EN: `local` matters: COMP_WORDS handlers run in the user's interactive
	// shell, and an unscoped variable named "i" or "w" would clobber theirs.
	// PT: `local` importa: handlers de COMP_WORDS rodam no shell interativo do
	// usuário, e uma variável sem escopo chamada "i" ou "w" atropelaria a dele.
	b.WriteString("    local cur key w i\n")
	b.WriteString("    COMPREPLY=()\n")
	b.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("\n")

	// EN: Bash hands over COMP_WORDS (the words typed) and COMP_CWORD (the index
	// of the one being completed). Walking 0..COMP_CWORD-1 and DROPPING anything
	// that starts with a dash rebuilds the command path:
	//
	//	task remote ad⇥       → key = "task remote"
	//	task -v remote ad⇥    → key = "task remote"   (-v skipped)
	//	task remote -v ad⇥    → key = "task remote"
	//
	// That is the same commutativity the parser has, in three lines of shell —
	// and not by coincidence: both fall out of treating flags and positionals
	// as independent lists.
	//
	// PT: O bash entrega COMP_WORDS (as palavras digitadas) e COMP_CWORD (o
	// índice da que está sendo completada). Percorrer 0..COMP_CWORD-1
	// DESCARTANDO o que começa com hífen reconstrói o caminho do comando. É a
	// mesma comutatividade do parser, em três linhas de shell — e não por
	// coincidência: as duas caem de tratar flags e posicionais como listas
	// independentes.
	b.WriteString("    # Rebuild the command path from the non-flag words typed so far,\n")
	b.WriteString("    # so flags anywhere on the line do not disturb the lookup.\n")
	b.WriteString("    key=\"\"\n")
	b.WriteString("    for ((i = 0; i < COMP_CWORD; i++)); do\n")
	b.WriteString("        w=\"${COMP_WORDS[i]}\"\n")
	b.WriteString("        [[ \"$w\" == -* ]] && continue\n")
	b.WriteString("        key=\"${key:+$key }$w\"\n")
	b.WriteString("    done\n")
	b.WriteString("\n")

	b.WriteString("    case \"$key\" in\n")
	for _, arm := range arms {
		b.WriteString(arm)
	}
	b.WriteString("    esac\n")
	b.WriteString("}\n\n")

	// EN: The line that actually registers the function with bash. Everything
	// above is inert until this runs.
	// PT: A linha que de fato registra a função no bash. Tudo acima é inerte até
	// isto rodar.
	b.WriteString("complete -F " + fn + " " + root.Name + "\n")

	return b.String()
}

// collectArms appends one case arm per node, depth first.
//
// EN — Same descending-accumulator walk as Validate in command.go: each node
// receives what its ancestors made persistent, adds its own, and passes a copy
// down. The third traversal of the tree in this package, and the third time the
// answer is the same shape.
//
// Two copies happen here, for the same reason in both cases — owning the array
// instead of writing into the caller's:
//
//	next       the inherited flag set handed to children
//	childPath  the path slice handed to each child
//
// PT — Mesma travessia com acumulador descendente do Validate em command.go:
// cada nó recebe o que os ancestrais tornaram persistente, acrescenta o próprio,
// e passa uma cópia para baixo. A terceira travessia da árvore neste pacote, e a
// terceira vez que a resposta tem a mesma forma.
//
// Duas cópias acontecem aqui, pela mesma razão nos dois casos — ser dono do
// array em vez de escrever no do chamador.
func collectArms(cmd *Command, path []string, inherited []Flag, arms *[]string) {
	// EN: %q on the key produces a quoted bash case pattern; %q on the word list
	// produces the quoted argument to compgen -W. Both need quoting because the
	// key contains spaces.
	// PT: %q na chave produz um padrão de case do bash entre aspas; %q na lista
	// de palavras produz o argumento entre aspas do compgen -W. Os dois precisam
	// de aspas porque a chave contém espaços.
	*arms = append(*arms, fmt.Sprintf(
		"        %q)\n            COMPREPLY=($(compgen -W %q -- \"$cur\"))\n            ;;\n",
		strings.Join(path, " "),
		strings.Join(completionWords(cmd, inherited), " "),
	))

	next := make([]Flag, len(inherited), len(inherited)+len(cmd.Flags))
	copy(next, inherited)
	for _, f := range cmd.Flags {
		if f.Persistent {
			next = append(next, f)
		}
	}

	for _, sub := range cmd.Sub {
		childPath := make([]string, len(path), len(path)+1)
		copy(childPath, path)
		collectArms(sub, append(childPath, sub.Name), next, arms)
	}
}

// completionWords is everything that can follow a command.
//
// EN — Three sources plus one constant:
//
//	cmd.Sub       the child command names
//	cmd.Flags     the flags declared here
//	inherited     the persistent flags from above
//	--help        always offered, because Parse always intercepts it
//
// --help is the one word not read from the tree, and it belongs here precisely
// because it is not in the tree: the parser synthesises it for any command that
// does not declare its own. A completion list that omitted it would hide a flag
// that actually works.
//
// The result is sorted so the generated script is byte-stable between runs —
// the same reason help sorts its sections.
//
// PT — Três fontes mais uma constante:
//
//	cmd.Sub       os nomes dos comandos filhos
//	cmd.Flags     as flags declaradas aqui
//	inherited     as persistentes de cima
//	--help        sempre oferecido, porque o Parse sempre o intercepta
//
// --help é a única palavra que não é lida da árvore, e pertence aqui justamente
// por não estar na árvore: o parser o sintetiza para qualquer comando que não
// declare o próprio. Uma lista de completion que o omitisse esconderia uma flag
// que de fato funciona.
//
// O resultado é ordenado para que o script gerado seja estável byte a byte entre
// execuções — a mesma razão de o help ordenar suas seções.
func completionWords(cmd *Command, inherited []Flag) []string {
	words := make([]string, 0, len(cmd.Sub)+len(cmd.Flags)+len(inherited)+1)

	for _, sub := range cmd.Sub {
		words = append(words, sub.Name)
	}
	for _, f := range cmd.Flags {
		words = append(words, "--"+f.Name)
	}
	for _, f := range inherited {
		words = append(words, "--"+f.Name)
	}
	words = append(words, "--help")

	sort.Strings(words)
	return words
}

// sanitize turns a command name into a valid bash function name fragment.
//
// EN — Shell function names accept far less than command names do. A CLI called
// "my-tool" would generate "_my-tool_completions", and bash reads the hyphen as
// a minus sign inside an arithmetic context — so every non-alphanumeric
// character becomes an underscore.
//
// It is deliberately conservative rather than exact: "_my_tool_completions" is
// a name nobody types, only bash sees, so there is no cost to over-replacing.
//
// PT — Nomes de função de shell aceitam bem menos que nomes de comando. Uma CLI
// chamada "my-tool" geraria "_my-tool_completions", e o bash lê o hífen como
// sinal de menos em contexto aritmético — então todo caractere não alfanumérico
// vira underscore.
//
// É deliberadamente conservador em vez de exato: "_my_tool_completions" é um
// nome que ninguém digita, só o bash vê, então não há custo em substituir demais.
func sanitize(name string) string {
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}
